# Site settings
title: 서울S수치과의원
email: gehoon@gmail.com
logo: SNU_BL_xs.png
description: 서울S수치과; 경력 21년의 치과보존학전문의; 충치(수복)치료/신경치료/보철/임플란트/잇몸치료
baseurl: "" # the subpath of your site, e.g. /blog
github_username: gehoon

# Build settings
#theme: jekyll-theme-cayman
markdown: kramdown

include: ['_pages']
